# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1369, 1065)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 721, 651))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 231, 161))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_SerialPorts = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_SerialPorts.setGeometry(QtCore.QRect(20, 50, 69, 22))
        self.comboBox_SerialPorts.setObjectName("comboBox_SerialPorts")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(140, 90, 91, 16))
        self.label_35.setObjectName("label_35")
        self.doubleSpinBox_UpdateTime = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_UpdateTime.setGeometry(QtCore.QRect(140, 110, 62, 22))
        self.doubleSpinBox_UpdateTime.setDecimals(3)
        self.doubleSpinBox_UpdateTime.setProperty("value", 0.005)
        self.doubleSpinBox_UpdateTime.setObjectName("doubleSpinBox_UpdateTime")
        self.comboBox_Baudrate = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Baudrate.setGeometry(QtCore.QRect(20, 110, 69, 22))
        self.comboBox_Baudrate.setObjectName("comboBox_Baudrate")
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        self.label_41.setGeometry(QtCore.QRect(20, 90, 51, 16))
        self.label_41.setObjectName("label_41")
        self.pushButton_UpdatePorts = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_UpdatePorts.setGeometry(QtCore.QRect(130, 42, 81, 31))
        self.pushButton_UpdatePorts.setObjectName("pushButton_UpdatePorts")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 20, 421, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textBrowser_Buffer = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_Buffer.setGeometry(QtCore.QRect(20, 50, 381, 91))
        self.textBrowser_Buffer.setObjectName("textBrowser_Buffer")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 200, 311, 101))
        self.groupBox_16.setObjectName("groupBox_16")
        self.spinBox_WheelPosMax = QtWidgets.QSpinBox(self.groupBox_16)
        self.spinBox_WheelPosMax.setGeometry(QtCore.QRect(20, 50, 71, 22))
        self.spinBox_WheelPosMax.setMaximum(10000)
        self.spinBox_WheelPosMax.setProperty("value", 994)
        self.spinBox_WheelPosMax.setObjectName("spinBox_WheelPosMax")
        self.label_29 = QtWidgets.QLabel(self.groupBox_16)
        self.label_29.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_16)
        self.label_30.setGeometry(QtCore.QRect(120, 30, 81, 16))
        self.label_30.setObjectName("label_30")
        self.spinBox_WheelPosMin = QtWidgets.QSpinBox(self.groupBox_16)
        self.spinBox_WheelPosMin.setGeometry(QtCore.QRect(120, 50, 71, 22))
        self.spinBox_WheelPosMin.setMaximum(10000)
        self.spinBox_WheelPosMin.setProperty("value", 50)
        self.spinBox_WheelPosMin.setObjectName("spinBox_WheelPosMin")
        self.label_49 = QtWidgets.QLabel(self.groupBox_16)
        self.label_49.setGeometry(QtCore.QRect(210, 30, 91, 16))
        self.label_49.setObjectName("label_49")
        self.lineEdit_CurrentWheelPos = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_CurrentWheelPos.setGeometry(QtCore.QRect(220, 50, 71, 21))
        self.lineEdit_CurrentWheelPos.setObjectName("lineEdit_CurrentWheelPos")
        self.groupBox_38 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_38.setGeometry(QtCore.QRect(350, 200, 121, 101))
        self.groupBox_38.setObjectName("groupBox_38")
        self.lineEdit_CalibrationConstant = QtWidgets.QLineEdit(self.groupBox_38)
        self.lineEdit_CalibrationConstant.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.lineEdit_CalibrationConstant.setObjectName("lineEdit_CalibrationConstant")
        self.label_64 = QtWidgets.QLabel(self.groupBox_38)
        self.label_64.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.label_64.setObjectName("label_64")
        self.groupBox_39 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_39.setGeometry(QtCore.QRect(500, 200, 191, 101))
        self.groupBox_39.setObjectName("groupBox_39")
        self.lineEdit_LastLap = QtWidgets.QLineEdit(self.groupBox_39)
        self.lineEdit_LastLap.setGeometry(QtCore.QRect(90, 20, 81, 21))
        self.lineEdit_LastLap.setObjectName("lineEdit_LastLap")
        self.lineEdit_CalibrationConstant_3 = QtWidgets.QLineEdit(self.groupBox_39)
        self.lineEdit_CalibrationConstant_3.setGeometry(QtCore.QRect(90, 60, 81, 21))
        self.lineEdit_CalibrationConstant_3.setObjectName("lineEdit_CalibrationConstant_3")
        self.label_70 = QtWidgets.QLabel(self.groupBox_39)
        self.label_70.setGeometry(QtCore.QRect(30, 20, 111, 21))
        self.label_70.setObjectName("label_70")
        self.lineEdit_SetupTrack = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupTrack.setGeometry(QtCore.QRect(110, 340, 111, 20))
        self.lineEdit_SetupTrack.setObjectName("lineEdit_SetupTrack")
        self.lineEdit_SetupDriver = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupDriver.setGeometry(QtCore.QRect(110, 370, 111, 20))
        self.lineEdit_SetupDriver.setObjectName("lineEdit_SetupDriver")
        self.lineEdit_SetupWingAttackAngle = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupWingAttackAngle.setGeometry(QtCore.QRect(330, 310, 111, 20))
        self.lineEdit_SetupWingAttackAngle.setObjectName("lineEdit_SetupWingAttackAngle")
        self.label_73 = QtWidgets.QLabel(self.tab)
        self.label_73.setGeometry(QtCore.QRect(470, 380, 111, 16))
        self.label_73.setObjectName("label_73")
        self.label_54 = QtWidgets.QLabel(self.tab)
        self.label_54.setGeometry(QtCore.QRect(230, 440, 111, 16))
        self.label_54.setObjectName("label_54")
        self.label_58 = QtWidgets.QLabel(self.tab)
        self.label_58.setGeometry(QtCore.QRect(260, 400, 111, 16))
        self.label_58.setObjectName("label_58")
        self.label_71 = QtWidgets.QLabel(self.tab)
        self.label_71.setGeometry(QtCore.QRect(290, 430, 111, 16))
        self.label_71.setObjectName("label_71")
        self.label_50 = QtWidgets.QLabel(self.tab)
        self.label_50.setGeometry(QtCore.QRect(70, 340, 111, 16))
        self.label_50.setObjectName("label_50")
        self.label_72 = QtWidgets.QLabel(self.tab)
        self.label_72.setGeometry(QtCore.QRect(460, 310, 111, 16))
        self.label_72.setObjectName("label_72")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(80, 310, 111, 16))
        self.label_32.setObjectName("label_32")
        self.lineEdit_SetupTirePressureFront = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupTirePressureFront.setGeometry(QtCore.QRect(330, 430, 111, 20))
        self.lineEdit_SetupTirePressureFront.setObjectName("lineEdit_SetupTirePressureFront")
        self.label_52 = QtWidgets.QLabel(self.tab)
        self.label_52.setGeometry(QtCore.QRect(40, 400, 111, 16))
        self.label_52.setObjectName("label_52")
        self.label_56 = QtWidgets.QLabel(self.tab)
        self.label_56.setGeometry(QtCore.QRect(260, 340, 111, 16))
        self.label_56.setObjectName("label_56")
        self.lineEdit_SetupTirePressureRear = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupTirePressureRear.setGeometry(QtCore.QRect(330, 460, 111, 20))
        self.lineEdit_SetupTirePressureRear.setObjectName("lineEdit_SetupTirePressureRear")
        self.lineEdit_SetupCar = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupCar.setGeometry(QtCore.QRect(110, 310, 111, 20))
        self.lineEdit_SetupCar.setObjectName("lineEdit_SetupCar")
        self.lineEdit_SetupTemperature = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupTemperature.setGeometry(QtCore.QRect(110, 400, 111, 20))
        self.lineEdit_SetupTemperature.setObjectName("lineEdit_SetupTemperature")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(70, 370, 111, 16))
        self.label_31.setObjectName("label_31")
        self.label_55 = QtWidgets.QLabel(self.tab)
        self.label_55.setGeometry(QtCore.QRect(260, 310, 71, 16))
        self.label_55.setObjectName("label_55")
        self.lineEdit_SetupEngineMap = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupEngineMap.setGeometry(QtCore.QRect(330, 340, 111, 20))
        self.lineEdit_SetupEngineMap.setObjectName("lineEdit_SetupEngineMap")
        self.lineEdit_SetupDifferential = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupDifferential.setGeometry(QtCore.QRect(330, 400, 111, 20))
        self.lineEdit_SetupDifferential.setObjectName("lineEdit_SetupDifferential")
        self.textEdit_SetupComments = QtWidgets.QTextEdit(self.tab)
        self.textEdit_SetupComments.setGeometry(QtCore.QRect(530, 310, 161, 51))
        self.textEdit_SetupComments.setObjectName("textEdit_SetupComments")
        self.label_53 = QtWidgets.QLabel(self.tab)
        self.label_53.setGeometry(QtCore.QRect(70, 430, 111, 16))
        self.label_53.setObjectName("label_53")
        self.lineEdit_SetupAcquisitionRate = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupAcquisitionRate.setGeometry(QtCore.QRect(560, 380, 111, 20))
        self.lineEdit_SetupAcquisitionRate.setObjectName("lineEdit_SetupAcquisitionRate")
        self.label_57 = QtWidgets.QLabel(self.tab)
        self.label_57.setGeometry(QtCore.QRect(260, 370, 111, 16))
        self.label_57.setObjectName("label_57")
        self.label_59 = QtWidgets.QLabel(self.tab)
        self.label_59.setGeometry(QtCore.QRect(290, 460, 111, 16))
        self.label_59.setObjectName("label_59")
        self.lineEdit_SetupAntiroll = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupAntiroll.setGeometry(QtCore.QRect(110, 430, 111, 20))
        self.lineEdit_SetupAntiroll.setObjectName("lineEdit_SetupAntiroll")
        self.lineEdit_SetupBalanceBar = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SetupBalanceBar.setGeometry(QtCore.QRect(330, 370, 111, 20))
        self.lineEdit_SetupBalanceBar.setObjectName("lineEdit_SetupBalanceBar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 490, 671, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_FileName = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_FileName.setGeometry(QtCore.QRect(30, 70, 371, 21))
        self.lineEdit_FileName.setObjectName("lineEdit_FileName")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(30, 50, 141, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(180, 20, 71, 16))
        self.label_13.setObjectName("label_13")
        self.pushButtonOpenFile = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonOpenFile.setGeometry(QtCore.QRect(410, 70, 75, 23))
        self.pushButtonOpenFile.setObjectName("pushButtonOpenFile")
        self.pushButton_SaveSetupValues = QtWidgets.QPushButton(self.tab)
        self.pushButton_SaveSetupValues.setGeometry(QtCore.QRect(540, 440, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SaveSetupValues.setFont(font)
        self.pushButton_SaveSetupValues.setObjectName("pushButton_SaveSetupValues")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 121, 211))
        self.groupBox_5.setObjectName("groupBox_5")
        self.progressBar_EngineTemperature = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_EngineTemperature.setGeometry(QtCore.QRect(20, 40, 31, 141))
        self.progressBar_EngineTemperature.setProperty("value", 24)
        self.progressBar_EngineTemperature.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_EngineTemperature.setObjectName("progressBar_EngineTemperature")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 160, 51, 16))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 250, 691, 321))
        self.groupBox_7.setObjectName("groupBox_7")
        self.graphicsView_EngineData = PlotWidget(self.groupBox_7)
        self.graphicsView_EngineData.setGeometry(QtCore.QRect(30, 21, 481, 281))
        self.graphicsView_EngineData.setObjectName("graphicsView_EngineData")
        self.checkBox_Voltage = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_Voltage.setGeometry(QtCore.QRect(560, 220, 70, 17))
        self.checkBox_Voltage.setObjectName("checkBox_Voltage")
        self.checkBox_FuelPressure = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_FuelPressure.setGeometry(QtCore.QRect(560, 190, 101, 17))
        self.checkBox_FuelPressure.setObjectName("checkBox_FuelPressure")
        self.checkBox_EngineTemperature = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_EngineTemperature.setGeometry(QtCore.QRect(560, 160, 91, 17))
        self.checkBox_EngineTemperature.setObjectName("checkBox_EngineTemperature")
        self.checkBox_OilPressure = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_OilPressure.setGeometry(QtCore.QRect(560, 130, 91, 17))
        self.checkBox_OilPressure.setObjectName("checkBox_OilPressure")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(270, 20, 121, 211))
        self.groupBox_9.setObjectName("groupBox_9")
        self.progressBar_FuelPressure = QtWidgets.QProgressBar(self.groupBox_9)
        self.progressBar_FuelPressure.setGeometry(QtCore.QRect(20, 40, 31, 141))
        self.progressBar_FuelPressure.setMaximum(6)
        self.progressBar_FuelPressure.setProperty("value", 0)
        self.progressBar_FuelPressure.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_FuelPressure.setObjectName("progressBar_FuelPressure")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_3.setGeometry(QtCore.QRect(60, 160, 61, 16))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(400, 20, 121, 211))
        self.groupBox_10.setObjectName("groupBox_10")
        self.progressBar_BatteryVoltage = QtWidgets.QProgressBar(self.groupBox_10)
        self.progressBar_BatteryVoltage.setGeometry(QtCore.QRect(20, 40, 41, 141))
        self.progressBar_BatteryVoltage.setMaximum(15)
        self.progressBar_BatteryVoltage.setProperty("value", -1)
        self.progressBar_BatteryVoltage.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_BatteryVoltage.setObjectName("progressBar_BatteryVoltage")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(70, 160, 41, 16))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(140, 20, 121, 211))
        self.groupBox_6.setObjectName("groupBox_6")
        self.progressBar_OilPressure = QtWidgets.QProgressBar(self.groupBox_6)
        self.progressBar_OilPressure.setGeometry(QtCore.QRect(20, 40, 31, 141))
        self.progressBar_OilPressure.setMaximum(8)
        self.progressBar_OilPressure.setProperty("value", 0)
        self.progressBar_OilPressure.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_OilPressure.setObjectName("progressBar_OilPressure")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(60, 160, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 160, 51, 16))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_17.setGeometry(QtCore.QRect(530, 20, 171, 211))
        self.groupBox_17.setObjectName("groupBox_17")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 30, 151, 41))
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.radioButton_FanRelay = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton_FanRelay.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.radioButton_FanRelay.setObjectName("radioButton_FanRelay")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_22.setGeometry(QtCore.QRect(10, 90, 151, 41))
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.radioButton_FuelPumpRelay = QtWidgets.QRadioButton(self.groupBox_22)
        self.radioButton_FuelPumpRelay.setGeometry(QtCore.QRect(20, 10, 101, 17))
        self.radioButton_FuelPumpRelay.setChecked(True)
        self.radioButton_FuelPumpRelay.setAutoExclusive(True)
        self.radioButton_FuelPumpRelay.setAutoRepeatDelay(300)
        self.radioButton_FuelPumpRelay.setObjectName("radioButton_FuelPumpRelay")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 150, 151, 41))
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.radioButton_SparkcutRelay = QtWidgets.QRadioButton(self.groupBox_23)
        self.radioButton_SparkcutRelay.setGeometry(QtCore.QRect(20, 10, 101, 17))
        self.radioButton_SparkcutRelay.setObjectName("radioButton_SparkcutRelay")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 370, 291, 201))
        self.groupBox_8.setObjectName("groupBox_8")
        self.dial_WheelPos = QtWidgets.QDial(self.groupBox_8)
        self.dial_WheelPos.setGeometry(QtCore.QRect(50, 30, 131, 161))
        self.dial_WheelPos.setMinimum(-120)
        self.dial_WheelPos.setMaximum(120)
        self.dial_WheelPos.setPageStep(10)
        self.dial_WheelPos.setInvertedAppearance(False)
        self.dial_WheelPos.setInvertedControls(True)
        self.dial_WheelPos.setObjectName("dial_WheelPos")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(180, 100, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setScaledContents(False)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setGeometry(QtCore.QRect(260, 100, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(450, 240, 231, 101))
        self.groupBox_11.setObjectName("groupBox_11")
        self.progressBar_TPS = QtWidgets.QProgressBar(self.groupBox_11)
        self.progressBar_TPS.setGeometry(QtCore.QRect(20, 32, 191, 31))
        self.progressBar_TPS.setProperty("value", 24)
        self.progressBar_TPS.setObjectName("progressBar_TPS")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 20, 421, 331))
        self.groupBox_12.setObjectName("groupBox_12")
        self.graphicsView_DiagramaGG = PlotWidget(self.groupBox_12)
        self.graphicsView_DiagramaGG.setGeometry(QtCore.QRect(20, 30, 371, 271))
        self.graphicsView_DiagramaGG.setObjectName("graphicsView_DiagramaGG")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(450, 20, 231, 201))
        self.groupBox_13.setObjectName("groupBox_13")
        self.progressBar_FrontBreakBalance = QtWidgets.QProgressBar(self.groupBox_13)
        self.progressBar_FrontBreakBalance.setGeometry(QtCore.QRect(40, 50, 171, 31))
        self.progressBar_FrontBreakBalance.setProperty("value", 24)
        self.progressBar_FrontBreakBalance.setObjectName("progressBar_FrontBreakBalance")
        self.label_67 = QtWidgets.QLabel(self.groupBox_13)
        self.label_67.setGeometry(QtCore.QRect(80, 110, 91, 16))
        self.label_67.setObjectName("label_67")
        self.label_66 = QtWidgets.QLabel(self.groupBox_13)
        self.label_66.setGeometry(QtCore.QRect(80, 30, 91, 16))
        self.label_66.setObjectName("label_66")
        self.progressBar_RearBreakBalance = QtWidgets.QProgressBar(self.groupBox_13)
        self.progressBar_RearBreakBalance.setGeometry(QtCore.QRect(40, 130, 171, 31))
        self.progressBar_RearBreakBalance.setProperty("value", 24)
        self.progressBar_RearBreakBalance.setObjectName("progressBar_RearBreakBalance")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_14.setGeometry(QtCore.QRect(320, 370, 171, 201))
        self.groupBox_14.setObjectName("groupBox_14")
        self.progressBar_FrontBreakPressure = QtWidgets.QProgressBar(self.groupBox_14)
        self.progressBar_FrontBreakPressure.setGeometry(QtCore.QRect(30, 40, 41, 141))
        self.progressBar_FrontBreakPressure.setMaximum(70)
        self.progressBar_FrontBreakPressure.setProperty("value", 24)
        self.progressBar_FrontBreakPressure.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_FrontBreakPressure.setObjectName("progressBar_FrontBreakPressure")
        self.label_36 = QtWidgets.QLabel(self.groupBox_14)
        self.label_36.setGeometry(QtCore.QRect(118, 160, 21, 14))
        self.label_36.setObjectName("label_36")
        self.label_65 = QtWidgets.QLabel(self.groupBox_14)
        self.label_65.setGeometry(QtCore.QRect(90, 160, 22, 14))
        self.label_65.setObjectName("label_65")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_15.setGeometry(QtCore.QRect(509, 370, 171, 201))
        self.groupBox_15.setObjectName("groupBox_15")
        self.progressBar_RearBreakPressure = QtWidgets.QProgressBar(self.groupBox_15)
        self.progressBar_RearBreakPressure.setGeometry(QtCore.QRect(30, 40, 41, 141))
        self.progressBar_RearBreakPressure.setMaximum(70)
        self.progressBar_RearBreakPressure.setProperty("value", 24)
        self.progressBar_RearBreakPressure.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RearBreakPressure.setObjectName("progressBar_RearBreakPressure")
        self.label_68 = QtWidgets.QLabel(self.groupBox_15)
        self.label_68.setGeometry(QtCore.QRect(118, 160, 21, 14))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_15)
        self.label_69.setGeometry(QtCore.QRect(90, 160, 22, 14))
        self.label_69.setObjectName("label_69")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_20.setGeometry(QtCore.QRect(30, 20, 661, 291))
        self.groupBox_20.setObjectName("groupBox_20")
        self.tableWidget_StrainGauge = QtWidgets.QTableWidget(self.groupBox_20)
        self.tableWidget_StrainGauge.setGeometry(QtCore.QRect(40, 50, 351, 211))
        self.tableWidget_StrainGauge.setObjectName("tableWidget_StrainGauge")
        self.tableWidget_StrainGauge.setColumnCount(3)
        self.tableWidget_StrainGauge.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(8, 2, item)
        self.tableWidget_StrainGauge.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_StrainGauge.verticalHeader().setDefaultSectionSize(20)
        self.progressBar_WeightDistribuition4 = QtWidgets.QProgressBar(self.groupBox_20)
        self.progressBar_WeightDistribuition4.setGeometry(QtCore.QRect(530, 180, 31, 61))
        self.progressBar_WeightDistribuition4.setMaximum(150)
        self.progressBar_WeightDistribuition4.setProperty("value", 24)
        self.progressBar_WeightDistribuition4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_WeightDistribuition4.setObjectName("progressBar_WeightDistribuition4")
        self.progressBar_WeightDistribuition3 = QtWidgets.QProgressBar(self.groupBox_20)
        self.progressBar_WeightDistribuition3.setGeometry(QtCore.QRect(470, 180, 31, 61))
        self.progressBar_WeightDistribuition3.setMaximum(150)
        self.progressBar_WeightDistribuition3.setProperty("value", 24)
        self.progressBar_WeightDistribuition3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_WeightDistribuition3.setObjectName("progressBar_WeightDistribuition3")
        self.progressBar_WeightDistribuition2 = QtWidgets.QProgressBar(self.groupBox_20)
        self.progressBar_WeightDistribuition2.setGeometry(QtCore.QRect(530, 90, 31, 61))
        self.progressBar_WeightDistribuition2.setMaximum(150)
        self.progressBar_WeightDistribuition2.setProperty("value", 24)
        self.progressBar_WeightDistribuition2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_WeightDistribuition2.setObjectName("progressBar_WeightDistribuition2")
        self.progressBar_WeightDistribuition1 = QtWidgets.QProgressBar(self.groupBox_20)
        self.progressBar_WeightDistribuition1.setGeometry(QtCore.QRect(470, 90, 31, 61))
        self.progressBar_WeightDistribuition1.setMaximum(150)
        self.progressBar_WeightDistribuition1.setProperty("value", 24)
        self.progressBar_WeightDistribuition1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_WeightDistribuition1.setObjectName("progressBar_WeightDistribuition1")
        self.label_129 = QtWidgets.QLabel(self.groupBox_20)
        self.label_129.setGeometry(QtCore.QRect(460, 40, 121, 16))
        self.label_129.setObjectName("label_129")
        self.tabWidget.addTab(self.tab_5, "")
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(1200, 560, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.pushButton_PauseProgram = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PauseProgram.setGeometry(QtCore.QRect(1180, 420, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_PauseProgram.setFont(font)
        self.pushButton_PauseProgram.setObjectName("pushButton_PauseProgram")
        self.pushButton_StartProgram = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StartProgram.setGeometry(QtCore.QRect(1180, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_StartProgram.setFont(font)
        self.pushButton_StartProgram.setObjectName("pushButton_StartProgram")
        self.groupBox_18 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_18.setGeometry(QtCore.QRect(750, 0, 401, 701))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.tableWidget_Package1 = QtWidgets.QTableWidget(self.groupBox_18)
        self.tableWidget_Package1.setGeometry(QtCore.QRect(20, 30, 351, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_Package1.setFont(font)
        self.tableWidget_Package1.setObjectName("tableWidget_Package1")
        self.tableWidget_Package1.setColumnCount(3)
        self.tableWidget_Package1.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(7, 2, item)
        self.tableWidget_Package1.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_Package1.verticalHeader().setDefaultSectionSize(20)
        self.label_38 = QtWidgets.QLabel(self.groupBox_18)
        self.label_38.setGeometry(QtCore.QRect(20, 10, 71, 20))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_18)
        self.label_39.setGeometry(QtCore.QRect(20, 220, 71, 20))
        self.label_39.setObjectName("label_39")
        self.tableWidget_Package2 = QtWidgets.QTableWidget(self.groupBox_18)
        self.tableWidget_Package2.setGeometry(QtCore.QRect(20, 240, 351, 241))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_Package2.setFont(font)
        self.tableWidget_Package2.setObjectName("tableWidget_Package2")
        self.tableWidget_Package2.setColumnCount(3)
        self.tableWidget_Package2.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(9, 2, item)
        self.tableWidget_Package2.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_Package2.verticalHeader().setDefaultSectionSize(20)
        self.label_44 = QtWidgets.QLabel(self.groupBox_18)
        self.label_44.setGeometry(QtCore.QRect(20, 480, 71, 20))
        self.label_44.setObjectName("label_44")
        self.tableWidget_Package3 = QtWidgets.QTableWidget(self.groupBox_18)
        self.tableWidget_Package3.setGeometry(QtCore.QRect(20, 500, 351, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_Package3.setFont(font)
        self.tableWidget_Package3.setObjectName("tableWidget_Package3")
        self.tableWidget_Package3.setColumnCount(3)
        self.tableWidget_Package3.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(7, 2, item)
        self.tableWidget_Package3.horizontalHeader().setDefaultSectionSize(110)
        self.tableWidget_Package3.verticalHeader().setDefaultSectionSize(20)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(1160, 150, 181, 81))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.pushButton_SaveFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SaveFile.setGeometry(QtCore.QRect(1180, 280, 91, 41))
        self.pushButton_SaveFile.setObjectName("pushButton_SaveFile")
        self.pushButton_StopSaveFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StopSaveFile.setGeometry(QtCore.QRect(1180, 230, 91, 41))
        self.pushButton_StopSaveFile.setObjectName("pushButton_StopSaveFile")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1200, 190, 91, 20))
        self.label_12.setObjectName("label_12")
        self.pushButton_Exit.raise_()
        self.pushButton_PauseProgram.raise_()
        self.pushButton_StartProgram.raise_()
        self.groupBox_18.raise_()
        self.label_28.raise_()
        self.tabWidget.raise_()
        self.pushButton_SaveFile.raise_()
        self.pushButton_StopSaveFile.raise_()
        self.label_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1369, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUpdate_Serial_Ports = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Serial_Ports.setObjectName("actionUpdate_Serial_Ports")
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionUpdate_Serial_Ports)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "XBEE SERIAL PORT SETTINGS"))
        self.label_2.setText(_translate("MainWindow", "Serial Resource Name"))
        self.label_35.setText(_translate("MainWindow", "Update Time [s]"))
        self.label_41.setText(_translate("MainWindow", "Baud Rate"))
        self.pushButton_UpdatePorts.setText(_translate("MainWindow", "Update Ports"))
        self.groupBox_3.setTitle(_translate("MainWindow", "DATA PACK"))
        self.label_3.setText(_translate("MainWindow", "String read at buffer"))
        self.groupBox_16.setTitle(_translate("MainWindow", "WHEEL POSITION CALIBRATION"))
        self.label_29.setText(_translate("MainWindow", "Wheel Pos Max"))
        self.label_30.setText(_translate("MainWindow", "Wheel Pos Min"))
        self.label_49.setText(_translate("MainWindow", "Current Wheel Pos"))
        self.groupBox_38.setTitle(_translate("MainWindow", "STRAIN GAUGE"))
        self.label_64.setText(_translate("MainWindow", "Calibration Constant"))
        self.groupBox_39.setTitle(_translate("MainWindow", "LAP TIME"))
        self.label_70.setText(_translate("MainWindow", "Last Lap"))
        self.label_73.setText(_translate("MainWindow", "Sample Rate (Hz):"))
        self.label_54.setText(_translate("MainWindow", "Tire Pressure"))
        self.label_58.setText(_translate("MainWindow", "Differential:"))
        self.label_71.setText(_translate("MainWindow", "Front:"))
        self.label_50.setText(_translate("MainWindow", "Track:"))
        self.label_72.setText(_translate("MainWindow", "Comments:"))
        self.label_32.setText(_translate("MainWindow", "Car:"))
        self.label_52.setText(_translate("MainWindow", "Temperature:"))
        self.label_56.setText(_translate("MainWindow", "Engine map:"))
        self.lineEdit_SetupCar.setText(_translate("MainWindow", "TR-06"))
        self.label_31.setText(_translate("MainWindow", "Driver:"))
        self.label_55.setText(_translate("MainWindow", "Wing attack"))
        self.label_53.setText(_translate("MainWindow", "Antiroll:"))
        self.label_57.setText(_translate("MainWindow", "Balance Bar:"))
        self.label_59.setText(_translate("MainWindow", "Rear:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "FILE SETTINGS"))
        self.label_11.setText(_translate("MainWindow", "File Name"))
        self.label_13.setText(_translate("MainWindow", "Choose File"))
        self.pushButtonOpenFile.setText(_translate("MainWindow", "ChooseFile"))
        self.pushButton_SaveSetupValues.setText(_translate("MainWindow", "SAVE VALUES"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))
        self.groupBox_5.setTitle(_translate("MainWindow", "ENGINE TEMPERATURE"))
        self.progressBar_EngineTemperature.setFormat(_translate("MainWindow", "%p"))
        self.label_6.setText(_translate("MainWindow", "49"))
        self.label_9.setText(_translate("MainWindow", "ºC"))
        self.groupBox_7.setTitle(_translate("MainWindow", "PLOT"))
        self.checkBox_Voltage.setText(_translate("MainWindow", "Voltage"))
        self.checkBox_FuelPressure.setText(_translate("MainWindow", "Fuel Pressure"))
        self.checkBox_EngineTemperature.setText(_translate("MainWindow", "Engine Temp."))
        self.checkBox_OilPressure.setText(_translate("MainWindow", "Oil Pressure"))
        self.groupBox_9.setTitle(_translate("MainWindow", "FUEL PRESSURE"))
        self.progressBar_FuelPressure.setFormat(_translate("MainWindow", "%p"))
        self.label_17.setText(_translate("MainWindow", "49"))
        self.label_18.setText(_translate("MainWindow", "Bar"))
        self.groupBox_10.setTitle(_translate("MainWindow", "BATTERY VOLTAGE"))
        self.progressBar_BatteryVoltage.setFormat(_translate("MainWindow", "%p"))
        self.label_15.setText(_translate("MainWindow", "49"))
        self.label_16.setText(_translate("MainWindow", "V"))
        self.groupBox_6.setTitle(_translate("MainWindow", "OIL PRESSURE"))
        self.progressBar_OilPressure.setFormat(_translate("MainWindow", "%p"))
        self.label_10.setText(_translate("MainWindow", "49"))
        self.label_8.setText(_translate("MainWindow", "Bar"))
        self.groupBox_17.setTitle(_translate("MainWindow", "RELAY ACTIVATION"))
        self.radioButton_FanRelay.setText(_translate("MainWindow", "Fan Relay"))
        self.radioButton_FuelPumpRelay.setText(_translate("MainWindow", "Fuel Pump Relay"))
        self.radioButton_SparkcutRelay.setText(_translate("MainWindow", "Sparkcut Relay"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Engine | Battery | Relay"))
        self.groupBox_8.setTitle(_translate("MainWindow", "WHEEL POS (Deg)"))
        self.label_19.setText(_translate("MainWindow", "1"))
        self.label_20.setText(_translate("MainWindow", "º"))
        self.groupBox_11.setTitle(_translate("MainWindow", "TPS"))
        self.progressBar_TPS.setFormat(_translate("MainWindow", "%p%"))
        self.groupBox_12.setTitle(_translate("MainWindow", "G - G DIAGRAM"))
        self.groupBox_13.setTitle(_translate("MainWindow", "BREAK BALANCE"))
        self.label_67.setText(_translate("MainWindow", "Rear Break"))
        self.label_66.setText(_translate("MainWindow", "Front Break"))
        self.groupBox_14.setTitle(_translate("MainWindow", "FRONT BREAK PRESSURE"))
        self.progressBar_FrontBreakPressure.setFormat(_translate("MainWindow", "%p"))
        self.label_36.setText(_translate("MainWindow", "Bar"))
        self.label_65.setText(_translate("MainWindow", "49"))
        self.groupBox_15.setTitle(_translate("MainWindow", "REAR BREAK PRESSURE"))
        self.progressBar_RearBreakPressure.setFormat(_translate("MainWindow", "%p"))
        self.label_68.setText(_translate("MainWindow", "Bar"))
        self.label_69.setText(_translate("MainWindow", "49"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Wheel | TPS | Brake"))
        self.groupBox_20.setTitle(_translate("MainWindow", "STRAIN GAUGE"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_StrainGauge.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATA"))
        item = self.tableWidget_StrainGauge.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALUE"))
        item = self.tableWidget_StrainGauge.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "UNITY"))
        __sortingEnabled = self.tableWidget_StrainGauge.isSortingEnabled()
        self.tableWidget_StrainGauge.setSortingEnabled(False)
        item = self.tableWidget_StrainGauge.item(0, 0)
        item.setText(_translate("MainWindow", "P1 Strain Gauge"))
        item = self.tableWidget_StrainGauge.item(0, 2)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(1, 0)
        item.setText(_translate("MainWindow", "P2 Strain Gauge"))
        item = self.tableWidget_StrainGauge.item(1, 2)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(2, 0)
        item.setText(_translate("MainWindow", "P3 Strain Gauge"))
        item = self.tableWidget_StrainGauge.item(2, 2)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(3, 0)
        item.setText(_translate("MainWindow", "P4 Strain Gauge"))
        item = self.tableWidget_StrainGauge.item(3, 2)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(4, 0)
        item.setText(_translate("MainWindow", "P5 Strain Gauge"))
        item = self.tableWidget_StrainGauge.item(4, 2)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(5, 0)
        item.setText(_translate("MainWindow", "P6 Strain Gauge"))
        item = self.tableWidget_StrainGauge.item(5, 2)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(6, 0)
        item.setText(_translate("MainWindow", "P7 Strain Gauge"))
        item = self.tableWidget_StrainGauge.item(6, 2)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(7, 0)
        item.setText(_translate("MainWindow", "P8 Strain Gauge"))
        item = self.tableWidget_StrainGauge.item(7, 2)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(8, 0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_StrainGauge.item(8, 2)
        item.setText(_translate("MainWindow", "ms"))
        self.tableWidget_StrainGauge.setSortingEnabled(__sortingEnabled)
        self.progressBar_WeightDistribuition4.setFormat(_translate("MainWindow", "%p"))
        self.progressBar_WeightDistribuition3.setFormat(_translate("MainWindow", "%p"))
        self.progressBar_WeightDistribuition2.setFormat(_translate("MainWindow", "%p"))
        self.progressBar_WeightDistribuition1.setFormat(_translate("MainWindow", "%p"))
        self.label_129.setText(_translate("MainWindow", "Weight Distribuition (Kg)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Strain Gauge"))
        self.pushButton_Exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_PauseProgram.setText(_translate("MainWindow", "PAUSE PROGRAM"))
        self.pushButton_StartProgram.setText(_translate("MainWindow", "START PROGRAM"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Data List"))
        item = self.tableWidget_Package1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_Package1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_Package1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_Package1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_Package1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_Package1.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_Package1.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_Package1.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_Package1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATA"))
        item = self.tableWidget_Package1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALUE"))
        item = self.tableWidget_Package1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "UNIT"))
        __sortingEnabled = self.tableWidget_Package1.isSortingEnabled()
        self.tableWidget_Package1.setSortingEnabled(False)
        item = self.tableWidget_Package1.item(0, 0)
        item.setText(_translate("MainWindow", "Acceleration X"))
        item = self.tableWidget_Package1.item(0, 2)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(1, 0)
        item.setText(_translate("MainWindow", "Acceleration Y"))
        item = self.tableWidget_Package1.item(1, 2)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(2, 0)
        item.setText(_translate("MainWindow", "Acceleration Z"))
        item = self.tableWidget_Package1.item(2, 2)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(3, 0)
        item.setText(_translate("MainWindow", "Front Speed"))
        item = self.tableWidget_Package1.item(3, 2)
        item.setText(_translate("MainWindow", "km/h"))
        item = self.tableWidget_Package1.item(4, 0)
        item.setText(_translate("MainWindow", "Rear Speed"))
        item = self.tableWidget_Package1.item(4, 2)
        item.setText(_translate("MainWindow", "km/h"))
        item = self.tableWidget_Package1.item(5, 0)
        item.setText(_translate("MainWindow", "Sparkcut Relay"))
        item = self.tableWidget_Package1.item(5, 2)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package1.item(6, 0)
        item.setText(_translate("MainWindow", "Suspention Pos."))
        item = self.tableWidget_Package1.item(6, 2)
        item.setText(_translate("MainWindow", "mm"))
        item = self.tableWidget_Package1.item(7, 0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_Package1.item(7, 2)
        item.setText(_translate("MainWindow", "ms"))
        self.tableWidget_Package1.setSortingEnabled(__sortingEnabled)
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>PACKAGE 1</p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>PACKAGE 2</p></body></html>"))
        item = self.tableWidget_Package2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_Package2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_Package2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_Package2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_Package2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_Package2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_Package2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_Package2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_Package2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_Package2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget_Package2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATA"))
        item = self.tableWidget_Package2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALUE"))
        item = self.tableWidget_Package2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "UNIT"))
        __sortingEnabled = self.tableWidget_Package2.isSortingEnabled()
        self.tableWidget_Package2.setSortingEnabled(False)
        item = self.tableWidget_Package2.item(0, 0)
        item.setText(_translate("MainWindow", "Beacon"))
        item = self.tableWidget_Package2.item(0, 2)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package2.item(1, 0)
        item.setText(_translate("MainWindow", "Break Pressure(F)"))
        item = self.tableWidget_Package2.item(1, 2)
        item.setText(_translate("MainWindow", "Bar"))
        item = self.tableWidget_Package2.item(2, 0)
        item.setText(_translate("MainWindow", "Break Pressure(R)"))
        item = self.tableWidget_Package2.item(2, 2)
        item.setText(_translate("MainWindow", "Bar"))
        item = self.tableWidget_Package2.item(3, 0)
        item.setText(_translate("MainWindow", "Current"))
        item = self.tableWidget_Package2.item(3, 2)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget_Package2.item(4, 0)
        item.setText(_translate("MainWindow", "Fuel Pressure"))
        item = self.tableWidget_Package2.item(4, 2)
        item.setText(_translate("MainWindow", "Bar"))
        item = self.tableWidget_Package2.item(5, 0)
        item.setText(_translate("MainWindow", "Oil Pressure"))
        item = self.tableWidget_Package2.item(5, 2)
        item.setText(_translate("MainWindow", "Bar"))
        item = self.tableWidget_Package2.item(6, 0)
        item.setText(_translate("MainWindow", "RPM"))
        item = self.tableWidget_Package2.item(6, 2)
        item.setText(_translate("MainWindow", "km/h"))
        item = self.tableWidget_Package2.item(7, 0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_Package2.item(7, 2)
        item.setText(_translate("MainWindow", "ms"))
        item = self.tableWidget_Package2.item(8, 0)
        item.setText(_translate("MainWindow", "TPS"))
        item = self.tableWidget_Package2.item(8, 2)
        item.setText(_translate("MainWindow", "%"))
        item = self.tableWidget_Package2.item(9, 0)
        item.setText(_translate("MainWindow", "Wheel Position"))
        item = self.tableWidget_Package2.item(9, 2)
        item.setText(_translate("MainWindow", "Degree ( º )"))
        self.tableWidget_Package2.setSortingEnabled(__sortingEnabled)
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p>PACKAGE 3</p></body></html>"))
        item = self.tableWidget_Package3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_Package3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_Package3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_Package3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_Package3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_Package3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_Package3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_Package3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_Package3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATA"))
        item = self.tableWidget_Package3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "VALUE"))
        item = self.tableWidget_Package3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "UNIT"))
        __sortingEnabled = self.tableWidget_Package3.isSortingEnabled()
        self.tableWidget_Package3.setSortingEnabled(False)
        item = self.tableWidget_Package3.item(0, 0)
        item.setText(_translate("MainWindow", "Battery Voltage"))
        item = self.tableWidget_Package3.item(0, 2)
        item.setText(_translate("MainWindow", "Volts"))
        item = self.tableWidget_Package3.item(1, 0)
        item.setText(_translate("MainWindow", "Break Temp. (F)"))
        item = self.tableWidget_Package3.item(1, 2)
        item.setText(_translate("MainWindow", "ºC"))
        item = self.tableWidget_Package3.item(2, 0)
        item.setText(_translate("MainWindow", "Break Temp. (R)"))
        item = self.tableWidget_Package3.item(2, 2)
        item.setText(_translate("MainWindow", "ºC"))
        item = self.tableWidget_Package3.item(3, 0)
        item.setText(_translate("MainWindow", "Engine Temp."))
        item = self.tableWidget_Package3.item(3, 2)
        item.setText(_translate("MainWindow", "ºC"))
        item = self.tableWidget_Package3.item(4, 0)
        item.setText(_translate("MainWindow", "Fan Realy"))
        item = self.tableWidget_Package3.item(4, 2)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package3.item(5, 0)
        item.setText(_translate("MainWindow", "Fuel Pump Relay"))
        item = self.tableWidget_Package3.item(5, 2)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package3.item(6, 0)
        item.setText(_translate("MainWindow", "Relay Box T"))
        item = self.tableWidget_Package3.item(6, 2)
        item.setText(_translate("MainWindow", "ºC"))
        item = self.tableWidget_Package3.item(7, 0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_Package3.item(7, 2)
        item.setText(_translate("MainWindow", "ms"))
        self.tableWidget_Package3.setSortingEnabled(__sortingEnabled)
        self.pushButton_SaveFile.setText(_translate("MainWindow", "SAVE"))
        self.pushButton_StopSaveFile.setText(_translate("MainWindow", "STOP SAVE"))
        self.label_12.setText(_translate("MainWindow", "Not saving..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUpdate_Serial_Ports.setText(_translate("MainWindow", "Update Serial Ports"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
