# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1328, 796)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 681, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 101, 201))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 23, 104, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_Baudrate = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Baudrate.setGeometry(QtCore.QRect(10, 150, 69, 20))
        self.comboBox_Baudrate.setObjectName("comboBox_Baudrate")
        self.comboBox_SerialPorts = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_SerialPorts.setGeometry(QtCore.QRect(10, 65, 69, 20))
        self.comboBox_SerialPorts.setObjectName("comboBox_SerialPorts")
        self.pushButton_UpdatePorts = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_UpdatePorts.setGeometry(QtCore.QRect(10, 91, 75, 23))
        self.pushButton_UpdatePorts.setObjectName("pushButton_UpdatePorts")
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        self.label_41.setGeometry(QtCore.QRect(10, 130, 50, 16))
        self.label_41.setObjectName("label_41")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 10, 401, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textBrowser_Buffer = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_Buffer.setGeometry(QtCore.QRect(10, 70, 381, 111))
        self.textBrowser_Buffer.setObjectName("textBrowser_Buffer")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.label_3.setObjectName("label_3")
        self.radioButton_bufferLog = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_bufferLog.setGeometry(QtCore.QRect(120, 20, 101, 21))
        self.radioButton_bufferLog.setChecked(False)
        self.radioButton_bufferLog.setAutoExclusive(False)
        self.radioButton_bufferLog.setObjectName("radioButton_bufferLog")
        self.radioButton_applyFunctions = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_applyFunctions.setGeometry(QtCore.QRect(280, 20, 101, 21))
        self.radioButton_applyFunctions.setChecked(True)
        self.radioButton_applyFunctions.setAutoExclusive(False)
        self.radioButton_applyFunctions.setObjectName("radioButton_applyFunctions")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 290, 201, 101))
        self.groupBox_16.setObjectName("groupBox_16")
        self.label_29 = QtWidgets.QLabel(self.groupBox_16)
        self.label_29.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_16)
        self.label_30.setGeometry(QtCore.QRect(120, 30, 81, 16))
        self.label_30.setObjectName("label_30")
        self.lineEdit_WheelPosMin = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_WheelPosMin.setGeometry(QtCore.QRect(120, 50, 71, 21))
        self.lineEdit_WheelPosMin.setObjectName("lineEdit_WheelPosMin")
        self.lineEdit_WheelPosMax = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_WheelPosMax.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.lineEdit_WheelPosMax.setObjectName("lineEdit_WheelPosMax")
        self.groupBox_38 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_38.setGeometry(QtCore.QRect(220, 290, 121, 101))
        self.groupBox_38.setObjectName("groupBox_38")
        self.lineEdit_CalibrationConstant = QtWidgets.QLineEdit(self.groupBox_38)
        self.lineEdit_CalibrationConstant.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.lineEdit_CalibrationConstant.setObjectName("lineEdit_CalibrationConstant")
        self.label_64 = QtWidgets.QLabel(self.groupBox_38)
        self.label_64.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.label_64.setObjectName("label_64")
        self.groupBox_39 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_39.setGeometry(QtCore.QRect(350, 290, 131, 101))
        self.groupBox_39.setObjectName("groupBox_39")
        self.lineEdit_LastLap = QtWidgets.QLineEdit(self.groupBox_39)
        self.lineEdit_LastLap.setGeometry(QtCore.QRect(70, 20, 51, 21))
        self.lineEdit_LastLap.setObjectName("lineEdit_LastLap")
        self.lineEdit_CalibrationConstant_3 = QtWidgets.QLineEdit(self.groupBox_39)
        self.lineEdit_CalibrationConstant_3.setGeometry(QtCore.QRect(70, 60, 51, 21))
        self.lineEdit_CalibrationConstant_3.setObjectName("lineEdit_CalibrationConstant_3")
        self.label_70 = QtWidgets.QLabel(self.groupBox_39)
        self.label_70.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_70.setObjectName("label_70")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 390, 671, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_SetupDriver = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupDriver.setGeometry(QtCore.QRect(80, 90, 111, 20))
        self.lineEdit_SetupDriver.setObjectName("lineEdit_SetupDriver")
        self.lineEdit_SetupAntiroll = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupAntiroll.setGeometry(QtCore.QRect(80, 150, 111, 20))
        self.lineEdit_SetupAntiroll.setObjectName("lineEdit_SetupAntiroll")
        self.label_57 = QtWidgets.QLabel(self.groupBox_2)
        self.label_57.setGeometry(QtCore.QRect(230, 90, 111, 16))
        self.label_57.setObjectName("label_57")
        self.lineEdit_SetupTemperature = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupTemperature.setGeometry(QtCore.QRect(80, 120, 111, 20))
        self.lineEdit_SetupTemperature.setObjectName("lineEdit_SetupTemperature")
        self.lineEdit_SetupBalanceBar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupBalanceBar.setGeometry(QtCore.QRect(300, 90, 111, 20))
        self.lineEdit_SetupBalanceBar.setObjectName("lineEdit_SetupBalanceBar")
        self.lineEdit_SampleRate2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SampleRate2.setGeometry(QtCore.QRect(530, 120, 41, 20))
        self.lineEdit_SampleRate2.setObjectName("lineEdit_SampleRate2")
        self.label_56 = QtWidgets.QLabel(self.groupBox_2)
        self.label_56.setGeometry(QtCore.QRect(230, 60, 111, 16))
        self.label_56.setObjectName("label_56")
        self.label_58 = QtWidgets.QLabel(self.groupBox_2)
        self.label_58.setGeometry(QtCore.QRect(230, 120, 111, 16))
        self.label_58.setObjectName("label_58")
        self.textEdit_SetupComments = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_SetupComments.setGeometry(QtCore.QRect(500, 30, 161, 51))
        self.textEdit_SetupComments.setObjectName("textEdit_SetupComments")
        self.lineEdit_SetupWingAttackAngle = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupWingAttackAngle.setGeometry(QtCore.QRect(300, 30, 111, 20))
        self.lineEdit_SetupWingAttackAngle.setObjectName("lineEdit_SetupWingAttackAngle")
        self.lineEdit_SampleRate1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SampleRate1.setGeometry(QtCore.QRect(530, 90, 41, 20))
        self.lineEdit_SampleRate1.setObjectName("lineEdit_SampleRate1")
        self.label_77 = QtWidgets.QLabel(self.groupBox_2)
        self.label_77.setGeometry(QtCore.QRect(590, 120, 21, 16))
        self.label_77.setObjectName("label_77")
        self.pushButton_SaveSetupValues = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_SaveSetupValues.setGeometry(QtCore.QRect(510, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SaveSetupValues.setFont(font)
        self.pushButton_SaveSetupValues.setObjectName("pushButton_SaveSetupValues")
        self.lineEdit_SampleRate4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SampleRate4.setGeometry(QtCore.QRect(610, 120, 41, 20))
        self.lineEdit_SampleRate4.setObjectName("lineEdit_SampleRate4")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(50, 30, 111, 16))
        self.label_32.setObjectName("label_32")
        self.label_59 = QtWidgets.QLabel(self.groupBox_2)
        self.label_59.setGeometry(QtCore.QRect(260, 180, 111, 16))
        self.label_59.setObjectName("label_59")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(40, 90, 111, 16))
        self.label_31.setObjectName("label_31")
        self.lineEdit_SetupTirePressureRear = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupTirePressureRear.setGeometry(QtCore.QRect(300, 180, 111, 20))
        self.lineEdit_SetupTirePressureRear.setObjectName("lineEdit_SetupTirePressureRear")
        self.label_75 = QtWidgets.QLabel(self.groupBox_2)
        self.label_75.setGeometry(QtCore.QRect(510, 120, 21, 16))
        self.label_75.setObjectName("label_75")
        self.label_52 = QtWidgets.QLabel(self.groupBox_2)
        self.label_52.setGeometry(QtCore.QRect(10, 120, 111, 16))
        self.label_52.setObjectName("label_52")
        self.label_50 = QtWidgets.QLabel(self.groupBox_2)
        self.label_50.setGeometry(QtCore.QRect(40, 60, 111, 16))
        self.label_50.setObjectName("label_50")
        self.label_74 = QtWidgets.QLabel(self.groupBox_2)
        self.label_74.setGeometry(QtCore.QRect(510, 90, 21, 16))
        self.label_74.setObjectName("label_74")
        self.label_55 = QtWidgets.QLabel(self.groupBox_2)
        self.label_55.setGeometry(QtCore.QRect(230, 30, 71, 16))
        self.label_55.setObjectName("label_55")
        self.label_71 = QtWidgets.QLabel(self.groupBox_2)
        self.label_71.setGeometry(QtCore.QRect(260, 150, 111, 16))
        self.label_71.setObjectName("label_71")
        self.label_54 = QtWidgets.QLabel(self.groupBox_2)
        self.label_54.setGeometry(QtCore.QRect(200, 160, 111, 16))
        self.label_54.setObjectName("label_54")
        self.label_53 = QtWidgets.QLabel(self.groupBox_2)
        self.label_53.setGeometry(QtCore.QRect(40, 150, 111, 16))
        self.label_53.setObjectName("label_53")
        self.lineEdit_SetupDifferential = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupDifferential.setGeometry(QtCore.QRect(300, 120, 111, 20))
        self.lineEdit_SetupDifferential.setObjectName("lineEdit_SetupDifferential")
        self.lineEdit_SetupTirePressureFront = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupTirePressureFront.setGeometry(QtCore.QRect(300, 150, 111, 20))
        self.lineEdit_SetupTirePressureFront.setObjectName("lineEdit_SetupTirePressureFront")
        self.label_76 = QtWidgets.QLabel(self.groupBox_2)
        self.label_76.setGeometry(QtCore.QRect(590, 90, 21, 16))
        self.label_76.setObjectName("label_76")
        self.label_72 = QtWidgets.QLabel(self.groupBox_2)
        self.label_72.setGeometry(QtCore.QRect(430, 30, 111, 16))
        self.label_72.setObjectName("label_72")
        self.lineEdit_SetupEngineMap = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupEngineMap.setGeometry(QtCore.QRect(300, 60, 111, 20))
        self.lineEdit_SetupEngineMap.setObjectName("lineEdit_SetupEngineMap")
        self.lineEdit_SampleRate3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SampleRate3.setGeometry(QtCore.QRect(610, 90, 41, 20))
        self.lineEdit_SampleRate3.setObjectName("lineEdit_SampleRate3")
        self.lineEdit_SetupTrack = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupTrack.setGeometry(QtCore.QRect(80, 60, 111, 20))
        self.lineEdit_SetupTrack.setObjectName("lineEdit_SetupTrack")
        self.label_73 = QtWidgets.QLabel(self.groupBox_2)
        self.label_73.setGeometry(QtCore.QRect(420, 110, 111, 16))
        self.label_73.setObjectName("label_73")
        self.lineEdit_SetupCar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SetupCar.setGeometry(QtCore.QRect(80, 30, 111, 20))
        self.lineEdit_SetupCar.setObjectName("lineEdit_SetupCar")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(30, 220, 141, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_FileName = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_FileName.setGeometry(QtCore.QRect(30, 240, 371, 21))
        self.lineEdit_FileName.setObjectName("lineEdit_FileName")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 220, 661, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.alarmlineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.alarmlineEdit.setGeometry(QtCore.QRect(250, 30, 51, 20))
        self.alarmlineEdit.setObjectName("alarmlineEdit")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(30, 30, 201, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.alarmComboBox = QtWidgets.QComboBox(self.widget)
        self.alarmComboBox.setObjectName("alarmComboBox")
        self.horizontalLayout_5.addWidget(self.alarmComboBox)
        self.alarmTypeComboBox = QtWidgets.QComboBox(self.widget)
        self.alarmTypeComboBox.setObjectName("alarmTypeComboBox")
        self.horizontalLayout_5.addWidget(self.alarmTypeComboBox)
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(380, 30, 221, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saveAlarmPushButton = QtWidgets.QPushButton(self.widget1)
        self.saveAlarmPushButton.setObjectName("saveAlarmPushButton")
        self.horizontalLayout_6.addWidget(self.saveAlarmPushButton)
        self.restoreDefaultAlarmPushButton = QtWidgets.QPushButton(self.widget1)
        self.restoreDefaultAlarmPushButton.setObjectName("restoreDefaultAlarmPushButton")
        self.horizontalLayout_6.addWidget(self.restoreDefaultAlarmPushButton)
        self.groupBox_30 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_30.setGeometry(QtCore.QRect(130, 10, 131, 201))
        self.groupBox_30.setObjectName("groupBox_30")
        self.label_35 = QtWidgets.QLabel(self.groupBox_30)
        self.label_35.setGeometry(QtCore.QRect(30, 20, 91, 16))
        self.label_35.setObjectName("label_35")
        self.doubleSpinBox_UpdateTime = QtWidgets.QDoubleSpinBox(self.groupBox_30)
        self.doubleSpinBox_UpdateTime.setGeometry(QtCore.QRect(30, 40, 62, 22))
        self.doubleSpinBox_UpdateTime.setDecimals(3)
        self.doubleSpinBox_UpdateTime.setProperty("value", 0.005)
        self.doubleSpinBox_UpdateTime.setObjectName("doubleSpinBox_UpdateTime")
        self.label_37 = QtWidgets.QLabel(self.groupBox_30)
        self.label_37.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_37.setObjectName("label_37")
        self.radioButton_updateInterface = QtWidgets.QRadioButton(self.groupBox_30)
        self.radioButton_updateInterface.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.radioButton_updateInterface.setChecked(True)
        self.radioButton_updateInterface.setObjectName("radioButton_updateInterface")
        self.widget2 = QtWidgets.QWidget(self.groupBox_30)
        self.widget2.setGeometry(QtCore.QRect(40, 110, 61, 81))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.updateCounterP1 = QtWidgets.QDoubleSpinBox(self.widget2)
        self.updateCounterP1.setDecimals(0)
        self.updateCounterP1.setProperty("value", 6.0)
        self.updateCounterP1.setObjectName("updateCounterP1")
        self.verticalLayout.addWidget(self.updateCounterP1)
        self.updateCounterP2 = QtWidgets.QDoubleSpinBox(self.widget2)
        self.updateCounterP2.setDecimals(0)
        self.updateCounterP2.setProperty("value", 3.0)
        self.updateCounterP2.setObjectName("updateCounterP2")
        self.verticalLayout.addWidget(self.updateCounterP2)
        self.updateCounterP3 = QtWidgets.QDoubleSpinBox(self.widget2)
        self.updateCounterP3.setDecimals(0)
        self.updateCounterP3.setProperty("value", 0.0)
        self.updateCounterP3.setObjectName("updateCounterP3")
        self.verticalLayout.addWidget(self.updateCounterP3)
        self.updateCounterP4 = QtWidgets.QDoubleSpinBox(self.widget2)
        self.updateCounterP4.setDecimals(0)
        self.updateCounterP4.setProperty("value", 3.0)
        self.updateCounterP4.setObjectName("updateCounterP4")
        self.verticalLayout.addWidget(self.updateCounterP4)
        self.widget3 = QtWidgets.QWidget(self.groupBox_30)
        self.widget3.setGeometry(QtCore.QRect(20, 110, 16, 81))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_40 = QtWidgets.QLabel(self.widget3)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_2.addWidget(self.label_40)
        self.label_42 = QtWidgets.QLabel(self.widget3)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_2.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.widget3)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_2.addWidget(self.label_43)
        self.label_45 = QtWidgets.QLabel(self.widget3)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_2.addWidget(self.label_45)
        self.groupBox_40 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_40.setGeometry(QtCore.QRect(490, 290, 151, 101))
        self.groupBox_40.setObjectName("groupBox_40")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 121, 211))
        self.groupBox_5.setObjectName("groupBox_5")
        self.progressBar_EngineTemperature = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_EngineTemperature.setGeometry(QtCore.QRect(20, 40, 31, 141))
        self.progressBar_EngineTemperature.setProperty("value", 24)
        self.progressBar_EngineTemperature.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_EngineTemperature.setObjectName("progressBar_EngineTemperature")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 160, 51, 16))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 250, 691, 321))
        self.groupBox_7.setObjectName("groupBox_7")
        self.graphicsView_EngineData = PlotWidget(self.groupBox_7)
        self.graphicsView_EngineData.setGeometry(QtCore.QRect(30, 21, 521, 281))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_EngineData.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_EngineData.setForegroundBrush(brush)
        self.graphicsView_EngineData.setObjectName("graphicsView_EngineData")
        self.checkBox_Voltage = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_Voltage.setGeometry(QtCore.QRect(560, 220, 70, 17))
        self.checkBox_Voltage.setObjectName("checkBox_Voltage")
        self.checkBox_FuelPressure = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_FuelPressure.setGeometry(QtCore.QRect(560, 190, 101, 17))
        self.checkBox_FuelPressure.setObjectName("checkBox_FuelPressure")
        self.checkBox_EngineTemperature = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_EngineTemperature.setGeometry(QtCore.QRect(560, 160, 91, 17))
        self.checkBox_EngineTemperature.setObjectName("checkBox_EngineTemperature")
        self.checkBox_OilPressure = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_OilPressure.setGeometry(QtCore.QRect(560, 130, 91, 17))
        self.checkBox_OilPressure.setObjectName("checkBox_OilPressure")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(270, 20, 121, 211))
        self.groupBox_9.setObjectName("groupBox_9")
        self.progressBar_FuelPressure = QtWidgets.QProgressBar(self.groupBox_9)
        self.progressBar_FuelPressure.setGeometry(QtCore.QRect(20, 40, 31, 141))
        self.progressBar_FuelPressure.setMaximum(6)
        self.progressBar_FuelPressure.setProperty("value", 0)
        self.progressBar_FuelPressure.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_FuelPressure.setObjectName("progressBar_FuelPressure")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_3.setGeometry(QtCore.QRect(60, 160, 61, 16))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(400, 20, 121, 211))
        self.groupBox_10.setObjectName("groupBox_10")
        self.progressBar_BatteryVoltage = QtWidgets.QProgressBar(self.groupBox_10)
        self.progressBar_BatteryVoltage.setGeometry(QtCore.QRect(20, 40, 41, 141))
        self.progressBar_BatteryVoltage.setMaximum(15)
        self.progressBar_BatteryVoltage.setProperty("value", -1)
        self.progressBar_BatteryVoltage.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_BatteryVoltage.setObjectName("progressBar_BatteryVoltage")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_2.setGeometry(QtCore.QRect(70, 160, 41, 16))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(140, 20, 121, 211))
        self.groupBox_6.setObjectName("groupBox_6")
        self.progressBar_OilPressure = QtWidgets.QProgressBar(self.groupBox_6)
        self.progressBar_OilPressure.setGeometry(QtCore.QRect(20, 40, 31, 141))
        self.progressBar_OilPressure.setMaximum(8)
        self.progressBar_OilPressure.setProperty("value", 0)
        self.progressBar_OilPressure.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_OilPressure.setObjectName("progressBar_OilPressure")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(60, 160, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 160, 51, 16))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_17.setGeometry(QtCore.QRect(530, 20, 171, 211))
        self.groupBox_17.setObjectName("groupBox_17")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 30, 121, 41))
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.radioButton_FanRelay = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton_FanRelay.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.radioButton_FanRelay.setObjectName("radioButton_FanRelay")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_22.setGeometry(QtCore.QRect(10, 90, 121, 41))
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.radioButton_FuelPumpRelay = QtWidgets.QRadioButton(self.groupBox_22)
        self.radioButton_FuelPumpRelay.setGeometry(QtCore.QRect(20, 10, 101, 17))
        self.radioButton_FuelPumpRelay.setChecked(True)
        self.radioButton_FuelPumpRelay.setAutoExclusive(True)
        self.radioButton_FuelPumpRelay.setAutoRepeatDelay(300)
        self.radioButton_FuelPumpRelay.setObjectName("radioButton_FuelPumpRelay")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 150, 121, 41))
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 370, 291, 201))
        self.groupBox_8.setObjectName("groupBox_8")
        self.dial_WheelPos = QtWidgets.QDial(self.groupBox_8)
        self.dial_WheelPos.setGeometry(QtCore.QRect(50, 30, 131, 161))
        self.dial_WheelPos.setMinimum(-120)
        self.dial_WheelPos.setMaximum(120)
        self.dial_WheelPos.setPageStep(10)
        self.dial_WheelPos.setInvertedAppearance(False)
        self.dial_WheelPos.setInvertedControls(True)
        self.dial_WheelPos.setObjectName("dial_WheelPos")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(180, 100, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setScaledContents(False)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setGeometry(QtCore.QRect(260, 100, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(450, 240, 231, 101))
        self.groupBox_11.setObjectName("groupBox_11")
        self.progressBar_TPS = QtWidgets.QProgressBar(self.groupBox_11)
        self.progressBar_TPS.setGeometry(QtCore.QRect(20, 32, 191, 31))
        self.progressBar_TPS.setProperty("value", 24)
        self.progressBar_TPS.setObjectName("progressBar_TPS")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(450, 20, 231, 201))
        self.groupBox_13.setObjectName("groupBox_13")
        self.progressBar_FrontBrakeBalance = QtWidgets.QProgressBar(self.groupBox_13)
        self.progressBar_FrontBrakeBalance.setGeometry(QtCore.QRect(40, 50, 171, 31))
        self.progressBar_FrontBrakeBalance.setProperty("value", 24)
        self.progressBar_FrontBrakeBalance.setObjectName("progressBar_FrontBrakeBalance")
        self.label_67 = QtWidgets.QLabel(self.groupBox_13)
        self.label_67.setGeometry(QtCore.QRect(80, 110, 91, 16))
        self.label_67.setObjectName("label_67")
        self.label_66 = QtWidgets.QLabel(self.groupBox_13)
        self.label_66.setGeometry(QtCore.QRect(80, 30, 91, 16))
        self.label_66.setObjectName("label_66")
        self.progressBar_RearBrakeBalance = QtWidgets.QProgressBar(self.groupBox_13)
        self.progressBar_RearBrakeBalance.setGeometry(QtCore.QRect(40, 130, 171, 31))
        self.progressBar_RearBrakeBalance.setProperty("value", 24)
        self.progressBar_RearBrakeBalance.setObjectName("progressBar_RearBrakeBalance")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_14.setGeometry(QtCore.QRect(320, 370, 171, 201))
        self.groupBox_14.setObjectName("groupBox_14")
        self.progressBar_FrontBreakPressure = QtWidgets.QProgressBar(self.groupBox_14)
        self.progressBar_FrontBreakPressure.setGeometry(QtCore.QRect(30, 40, 41, 141))
        self.progressBar_FrontBreakPressure.setMaximum(70)
        self.progressBar_FrontBreakPressure.setProperty("value", 24)
        self.progressBar_FrontBreakPressure.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_FrontBreakPressure.setObjectName("progressBar_FrontBreakPressure")
        self.label_36 = QtWidgets.QLabel(self.groupBox_14)
        self.label_36.setGeometry(QtCore.QRect(118, 160, 21, 14))
        self.label_36.setObjectName("label_36")
        self.label_65 = QtWidgets.QLabel(self.groupBox_14)
        self.label_65.setGeometry(QtCore.QRect(90, 160, 22, 14))
        self.label_65.setObjectName("label_65")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_15.setGeometry(QtCore.QRect(509, 370, 171, 201))
        self.groupBox_15.setObjectName("groupBox_15")
        self.progressBar_RearBreakPressure = QtWidgets.QProgressBar(self.groupBox_15)
        self.progressBar_RearBreakPressure.setGeometry(QtCore.QRect(30, 40, 41, 141))
        self.progressBar_RearBreakPressure.setMaximum(70)
        self.progressBar_RearBreakPressure.setProperty("value", 24)
        self.progressBar_RearBreakPressure.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_RearBreakPressure.setObjectName("progressBar_RearBreakPressure")
        self.label_68 = QtWidgets.QLabel(self.groupBox_15)
        self.label_68.setGeometry(QtCore.QRect(118, 160, 21, 14))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_15)
        self.label_69.setGeometry(QtCore.QRect(90, 160, 22, 14))
        self.label_69.setObjectName("label_69")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_12.setGeometry(QtCore.QRect(0, 10, 321, 291))
        self.groupBox_12.setObjectName("groupBox_12")
        self.graphicsView_DiagramaGG_DD = PlotWidget(self.groupBox_12)
        self.graphicsView_DiagramaGG_DD.setGeometry(QtCore.QRect(10, 20, 301, 261))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_DD.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_DD.setForegroundBrush(brush)
        self.graphicsView_DiagramaGG_DD.setObjectName("graphicsView_DiagramaGG_DD")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_19.setGeometry(QtCore.QRect(320, 210, 321, 281))
        self.groupBox_19.setObjectName("groupBox_19")
        self.graphicsView_DiagramaGG_2 = PlotWidget(self.groupBox_19)
        self.graphicsView_DiagramaGG_2.setGeometry(QtCore.QRect(10, 10, 301, 261))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_2.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_2.setForegroundBrush(brush)
        self.graphicsView_DiagramaGG_2.setObjectName("graphicsView_DiagramaGG_2")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_24.setGeometry(QtCore.QRect(340, 10, 321, 291))
        self.groupBox_24.setObjectName("groupBox_24")
        self.graphicsView_DiagramaGG_DE = PlotWidget(self.groupBox_24)
        self.graphicsView_DiagramaGG_DE.setGeometry(QtCore.QRect(10, 20, 301, 261))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_DE.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_DE.setForegroundBrush(brush)
        self.graphicsView_DiagramaGG_DE.setObjectName("graphicsView_DiagramaGG_DE")
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_24)
        self.groupBox_25.setGeometry(QtCore.QRect(320, 210, 321, 281))
        self.groupBox_25.setObjectName("groupBox_25")
        self.graphicsView_DiagramaGG_4 = PlotWidget(self.groupBox_25)
        self.graphicsView_DiagramaGG_4.setGeometry(QtCore.QRect(10, 10, 301, 261))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_4.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_4.setForegroundBrush(brush)
        self.graphicsView_DiagramaGG_4.setObjectName("graphicsView_DiagramaGG_4")
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_26.setGeometry(QtCore.QRect(0, 310, 321, 291))
        self.groupBox_26.setObjectName("groupBox_26")
        self.graphicsView_DiagramaGG_TD = PlotWidget(self.groupBox_26)
        self.graphicsView_DiagramaGG_TD.setGeometry(QtCore.QRect(10, 20, 301, 261))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_TD.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_TD.setForegroundBrush(brush)
        self.graphicsView_DiagramaGG_TD.setObjectName("graphicsView_DiagramaGG_TD")
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_26)
        self.groupBox_27.setGeometry(QtCore.QRect(320, 210, 321, 281))
        self.groupBox_27.setObjectName("groupBox_27")
        self.graphicsView_DiagramaGG_6 = PlotWidget(self.groupBox_27)
        self.graphicsView_DiagramaGG_6.setGeometry(QtCore.QRect(10, 10, 301, 261))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_6.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_6.setForegroundBrush(brush)
        self.graphicsView_DiagramaGG_6.setObjectName("graphicsView_DiagramaGG_6")
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_28.setGeometry(QtCore.QRect(340, 310, 321, 291))
        self.groupBox_28.setObjectName("groupBox_28")
        self.graphicsView_DiagramaGG_TE = PlotWidget(self.groupBox_28)
        self.graphicsView_DiagramaGG_TE.setGeometry(QtCore.QRect(10, 20, 301, 261))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_TE.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_TE.setForegroundBrush(brush)
        self.graphicsView_DiagramaGG_TE.setObjectName("graphicsView_DiagramaGG_TE")
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_28)
        self.groupBox_29.setGeometry(QtCore.QRect(320, 210, 321, 281))
        self.groupBox_29.setObjectName("groupBox_29")
        self.graphicsView_DiagramaGG_8 = PlotWidget(self.groupBox_29)
        self.graphicsView_DiagramaGG_8.setGeometry(QtCore.QRect(10, 10, 301, 261))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_8.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_DiagramaGG_8.setForegroundBrush(brush)
        self.graphicsView_DiagramaGG_8.setObjectName("graphicsView_DiagramaGG_8")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_20.setGeometry(QtCore.QRect(30, 20, 661, 341))
        self.groupBox_20.setObjectName("groupBox_20")
        self.progressBar_WeightDistribuition4 = QtWidgets.QProgressBar(self.groupBox_20)
        self.progressBar_WeightDistribuition4.setGeometry(QtCore.QRect(530, 180, 31, 61))
        self.progressBar_WeightDistribuition4.setMaximum(150)
        self.progressBar_WeightDistribuition4.setProperty("value", 24)
        self.progressBar_WeightDistribuition4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_WeightDistribuition4.setObjectName("progressBar_WeightDistribuition4")
        self.progressBar_WeightDistribuition3 = QtWidgets.QProgressBar(self.groupBox_20)
        self.progressBar_WeightDistribuition3.setGeometry(QtCore.QRect(470, 180, 31, 61))
        self.progressBar_WeightDistribuition3.setMaximum(150)
        self.progressBar_WeightDistribuition3.setProperty("value", 24)
        self.progressBar_WeightDistribuition3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_WeightDistribuition3.setObjectName("progressBar_WeightDistribuition3")
        self.progressBar_WeightDistribuition2 = QtWidgets.QProgressBar(self.groupBox_20)
        self.progressBar_WeightDistribuition2.setGeometry(QtCore.QRect(530, 90, 31, 61))
        self.progressBar_WeightDistribuition2.setMaximum(150)
        self.progressBar_WeightDistribuition2.setProperty("value", 24)
        self.progressBar_WeightDistribuition2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_WeightDistribuition2.setObjectName("progressBar_WeightDistribuition2")
        self.progressBar_WeightDistribuition1 = QtWidgets.QProgressBar(self.groupBox_20)
        self.progressBar_WeightDistribuition1.setGeometry(QtCore.QRect(470, 90, 31, 61))
        self.progressBar_WeightDistribuition1.setMaximum(150)
        self.progressBar_WeightDistribuition1.setProperty("value", 24)
        self.progressBar_WeightDistribuition1.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_WeightDistribuition1.setObjectName("progressBar_WeightDistribuition1")
        self.label_129 = QtWidgets.QLabel(self.groupBox_20)
        self.label_129.setGeometry(QtCore.QRect(460, 40, 121, 16))
        self.label_129.setObjectName("label_129")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.errorLog = QtWidgets.QTextBrowser(self.tab_4)
        self.errorLog.setGeometry(QtCore.QRect(0, 50, 671, 551))
        self.errorLog.setObjectName("errorLog")
        self.radioButton_errorLog = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_errorLog.setGeometry(QtCore.QRect(50, 20, 81, 21))
        self.radioButton_errorLog.setChecked(False)
        self.radioButton_errorLog.setObjectName("radioButton_errorLog")
        self.tabWidget.addTab(self.tab_4, "")
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(1240, 560, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.pushButton_PauseProgram = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PauseProgram.setGeometry(QtCore.QRect(1230, 420, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_PauseProgram.setFont(font)
        self.pushButton_PauseProgram.setObjectName("pushButton_PauseProgram")
        self.pushButton_StartProgram = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StartProgram.setGeometry(QtCore.QRect(1230, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_StartProgram.setFont(font)
        self.pushButton_StartProgram.setObjectName("pushButton_StartProgram")
        self.groupBox_18 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_18.setGeometry(QtCore.QRect(690, 0, 541, 751))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.tableWidget_Package1 = QtWidgets.QTableWidget(self.groupBox_18)
        self.tableWidget_Package1.setGeometry(QtCore.QRect(20, 30, 251, 411))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_Package1.setFont(font)
        self.tableWidget_Package1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_Package1.setShowGrid(True)
        self.tableWidget_Package1.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_Package1.setWordWrap(True)
        self.tableWidget_Package1.setObjectName("tableWidget_Package1")
        self.tableWidget_Package1.setColumnCount(2)
        self.tableWidget_Package1.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package1.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package1.setItem(18, 1, item)
        self.tableWidget_Package1.horizontalHeader().setVisible(True)
        self.tableWidget_Package1.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget_Package1.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Package1.verticalHeader().setDefaultSectionSize(20)
        self.label_38 = QtWidgets.QLabel(self.groupBox_18)
        self.label_38.setGeometry(QtCore.QRect(30, 30, 41, 20))
        self.label_38.setObjectName("label_38")
        self.tableWidget_Package2 = QtWidgets.QTableWidget(self.groupBox_18)
        self.tableWidget_Package2.setGeometry(QtCore.QRect(270, 420, 271, 331))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_Package2.setFont(font)
        self.tableWidget_Package2.setObjectName("tableWidget_Package2")
        self.tableWidget_Package2.setColumnCount(2)
        self.tableWidget_Package2.setRowCount(15)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package2.setItem(14, 1, item)
        self.tableWidget_Package2.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget_Package2.verticalHeader().setDefaultSectionSize(20)
        self.label_44 = QtWidgets.QLabel(self.groupBox_18)
        self.label_44.setGeometry(QtCore.QRect(290, 420, 71, 20))
        self.label_44.setObjectName("label_44")
        self.label_39 = QtWidgets.QLabel(self.groupBox_18)
        self.label_39.setGeometry(QtCore.QRect(290, 30, 71, 20))
        self.label_39.setObjectName("label_39")
        self.tableWidget_Package3 = QtWidgets.QTableWidget(self.groupBox_18)
        self.tableWidget_Package3.setGeometry(QtCore.QRect(270, 30, 271, 391))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_Package3.setFont(font)
        self.tableWidget_Package3.setObjectName("tableWidget_Package3")
        self.tableWidget_Package3.setColumnCount(2)
        self.tableWidget_Package3.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Package3.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_Package3.setItem(17, 1, item)
        self.tableWidget_Package3.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget_Package3.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Package3.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_StrainGauge = QtWidgets.QTableWidget(self.groupBox_18)
        self.tableWidget_StrainGauge.setGeometry(QtCore.QRect(20, 440, 251, 291))
        self.tableWidget_StrainGauge.setObjectName("tableWidget_StrainGauge")
        self.tableWidget_StrainGauge.setColumnCount(2)
        self.tableWidget_StrainGauge.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StrainGauge.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_StrainGauge.setItem(12, 1, item)
        self.tableWidget_StrainGauge.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget_StrainGauge.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_Package1.raise_()
        self.label_38.raise_()
        self.tableWidget_Package2.raise_()
        self.tableWidget_Package3.raise_()
        self.label_44.raise_()
        self.label_39.raise_()
        self.tableWidget_StrainGauge.raise_()
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(1160, 150, 181, 81))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.pushButton_SaveFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SaveFile.setGeometry(QtCore.QRect(1250, 280, 91, 41))
        self.pushButton_SaveFile.setObjectName("pushButton_SaveFile")
        self.pushButton_StopSaveFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StopSaveFile.setGeometry(QtCore.QRect(1250, 230, 91, 41))
        self.pushButton_StopSaveFile.setObjectName("pushButton_StopSaveFile")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1270, 200, 91, 20))
        self.label_12.setObjectName("label_12")
        self.pushButton_Exit.raise_()
        self.pushButton_PauseProgram.raise_()
        self.pushButton_StartProgram.raise_()
        self.groupBox_18.raise_()
        self.label_28.raise_()
        self.tabWidget.raise_()
        self.pushButton_SaveFile.raise_()
        self.pushButton_StopSaveFile.raise_()
        self.label_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1328, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUpdate_Serial_Ports = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Serial_Ports.setObjectName("actionUpdate_Serial_Ports")
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionUpdate_Serial_Ports)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "SERIAL PORT"))
        self.label_2.setText(_translate("MainWindow", "Serial Res. Name"))
        self.pushButton_UpdatePorts.setText(_translate("MainWindow", "Update Ports"))
        self.label_41.setText(_translate("MainWindow", "Baud Rate"))
        self.groupBox_3.setTitle(_translate("MainWindow", "DATA STREAM"))
        self.label_3.setText(_translate("MainWindow", "Incoming buffers"))
        self.radioButton_bufferLog.setText(_translate("MainWindow", "BufferView ON"))
        self.radioButton_applyFunctions.setText(_translate("MainWindow", "Apply Functions"))
        self.groupBox_16.setTitle(_translate("MainWindow", "WHEEL POSITION CALIBRATION"))
        self.label_29.setText(_translate("MainWindow", "Wheel Pos Max"))
        self.label_30.setText(_translate("MainWindow", "Wheel Pos Min"))
        self.lineEdit_WheelPosMin.setText(_translate("MainWindow", "200"))
        self.lineEdit_WheelPosMax.setText(_translate("MainWindow", "1000"))
        self.groupBox_38.setTitle(_translate("MainWindow", "STRAIN GAUGE"))
        self.label_64.setText(_translate("MainWindow", "Calibration Constant"))
        self.groupBox_39.setTitle(_translate("MainWindow", "LAP TIME"))
        self.label_70.setText(_translate("MainWindow", "Last Lap"))
        self.groupBox_2.setTitle(_translate("MainWindow", "FILE SETTINGS"))
        self.label_57.setText(_translate("MainWindow", "Balance Bar:"))
        self.lineEdit_SampleRate2.setText(_translate("MainWindow", "20"))
        self.label_56.setText(_translate("MainWindow", "Engine map:"))
        self.label_58.setText(_translate("MainWindow", "Differential:"))
        self.lineEdit_SampleRate1.setText(_translate("MainWindow", "40"))
        self.label_77.setText(_translate("MainWindow", "P4"))
        self.pushButton_SaveSetupValues.setText(_translate("MainWindow", "SAVE VALUES"))
        self.lineEdit_SampleRate4.setText(_translate("MainWindow", "20"))
        self.label_32.setText(_translate("MainWindow", "Car:"))
        self.label_59.setText(_translate("MainWindow", "Rear:"))
        self.label_31.setText(_translate("MainWindow", "Driver:"))
        self.label_75.setText(_translate("MainWindow", "P2"))
        self.label_52.setText(_translate("MainWindow", "Temperature:"))
        self.label_50.setText(_translate("MainWindow", "Track:"))
        self.label_74.setText(_translate("MainWindow", "P1"))
        self.label_55.setText(_translate("MainWindow", "Wing attack"))
        self.label_71.setText(_translate("MainWindow", "Front:"))
        self.label_54.setText(_translate("MainWindow", "Tire Pressure"))
        self.label_53.setText(_translate("MainWindow", "Antiroll:"))
        self.label_76.setText(_translate("MainWindow", "P3"))
        self.label_72.setText(_translate("MainWindow", "Comments:"))
        self.lineEdit_SampleRate3.setText(_translate("MainWindow", "2"))
        self.label_73.setText(_translate("MainWindow", "Sample Rates (Hz):"))
        self.lineEdit_SetupCar.setText(_translate("MainWindow", "TR-06"))
        self.label_11.setText(_translate("MainWindow", "File Name"))
        self.groupBox_4.setTitle(_translate("MainWindow", "ALARM TRIGGER CONFIG"))
        self.saveAlarmPushButton.setText(_translate("MainWindow", "SAVE"))
        self.restoreDefaultAlarmPushButton.setText(_translate("MainWindow", "RESTORE DEAFULT"))
        self.groupBox_30.setTitle(_translate("MainWindow", "INTERFACE UPDATE"))
        self.label_35.setText(_translate("MainWindow", "Update Time [s]"))
        self.label_37.setText(_translate("MainWindow", "Update Counter"))
        self.radioButton_updateInterface.setText(_translate("MainWindow", "Update Interface"))
        self.label_40.setText(_translate("MainWindow", "P1"))
        self.label_42.setText(_translate("MainWindow", "P2"))
        self.label_43.setText(_translate("MainWindow", "P3"))
        self.label_45.setText(_translate("MainWindow", "P4"))
        self.groupBox_40.setTitle(_translate("MainWindow", "LAP TIME"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))
        self.groupBox_5.setTitle(_translate("MainWindow", "ENGINE TEMPERATURE"))
        self.progressBar_EngineTemperature.setFormat(_translate("MainWindow", "%p"))
        self.label_6.setText(_translate("MainWindow", "49"))
        self.label_9.setText(_translate("MainWindow", "ºC"))
        self.groupBox_7.setTitle(_translate("MainWindow", "PLOT"))
        self.checkBox_Voltage.setText(_translate("MainWindow", "Voltage"))
        self.checkBox_FuelPressure.setText(_translate("MainWindow", "Fuel Pressure"))
        self.checkBox_EngineTemperature.setText(_translate("MainWindow", "Engine Temp."))
        self.checkBox_OilPressure.setText(_translate("MainWindow", "Oil Pressure"))
        self.groupBox_9.setTitle(_translate("MainWindow", "FUEL PRESSURE"))
        self.progressBar_FuelPressure.setFormat(_translate("MainWindow", "%p"))
        self.label_17.setText(_translate("MainWindow", "49"))
        self.label_18.setText(_translate("MainWindow", "Bar"))
        self.groupBox_10.setTitle(_translate("MainWindow", "BATTERY VOLTAGE"))
        self.progressBar_BatteryVoltage.setFormat(_translate("MainWindow", "%p"))
        self.label_15.setText(_translate("MainWindow", "49"))
        self.label_16.setText(_translate("MainWindow", "V"))
        self.groupBox_6.setTitle(_translate("MainWindow", "OIL PRESSURE"))
        self.progressBar_OilPressure.setFormat(_translate("MainWindow", "%p"))
        self.label_10.setText(_translate("MainWindow", "49"))
        self.label_8.setText(_translate("MainWindow", "Bar"))
        self.groupBox_17.setTitle(_translate("MainWindow", "MOS ACTIVATION"))
        self.radioButton_FanRelay.setText(_translate("MainWindow", "Fan MOS"))
        self.radioButton_FuelPumpRelay.setText(_translate("MainWindow", "Fuel Pump MOS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Engine | Battery | Relay"))
        self.groupBox_8.setTitle(_translate("MainWindow", "WHEEL POS (Deg)"))
        self.label_19.setText(_translate("MainWindow", "1"))
        self.label_20.setText(_translate("MainWindow", "º"))
        self.groupBox_11.setTitle(_translate("MainWindow", "TPS"))
        self.progressBar_TPS.setFormat(_translate("MainWindow", "%p%"))
        self.groupBox_13.setTitle(_translate("MainWindow", "BRAKE BALANCE"))
        self.label_67.setText(_translate("MainWindow", "Rear Break"))
        self.label_66.setText(_translate("MainWindow", "Front Break"))
        self.groupBox_14.setTitle(_translate("MainWindow", "FRONT BREAK PRESSURE"))
        self.progressBar_FrontBreakPressure.setFormat(_translate("MainWindow", "%p"))
        self.label_36.setText(_translate("MainWindow", "Bar"))
        self.label_65.setText(_translate("MainWindow", "49"))
        self.groupBox_15.setTitle(_translate("MainWindow", "REAR BREAK PRESSURE"))
        self.progressBar_RearBreakPressure.setFormat(_translate("MainWindow", "%p"))
        self.label_68.setText(_translate("MainWindow", "Bar"))
        self.label_69.setText(_translate("MainWindow", "49"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Wheel | TPS | Brake"))
        self.groupBox_12.setTitle(_translate("MainWindow", "G - G DIAGRAM DD"))
        self.groupBox_19.setTitle(_translate("MainWindow", "G - G DIAGRAM"))
        self.groupBox_24.setTitle(_translate("MainWindow", "G - G DIAGRAM DE"))
        self.groupBox_25.setTitle(_translate("MainWindow", "G - G DIAGRAM"))
        self.groupBox_26.setTitle(_translate("MainWindow", "G - G DIAGRAM TD"))
        self.groupBox_27.setTitle(_translate("MainWindow", "G - G DIAGRAM"))
        self.groupBox_28.setTitle(_translate("MainWindow", "G - G DIAGRAM TE"))
        self.groupBox_29.setTitle(_translate("MainWindow", "G - G DIAGRAM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "GG"))
        self.groupBox_20.setTitle(_translate("MainWindow", "STRAIN GAUGE"))
        self.progressBar_WeightDistribuition4.setFormat(_translate("MainWindow", "%p"))
        self.progressBar_WeightDistribuition3.setFormat(_translate("MainWindow", "%p"))
        self.progressBar_WeightDistribuition2.setFormat(_translate("MainWindow", "%p"))
        self.progressBar_WeightDistribuition1.setFormat(_translate("MainWindow", "%p"))
        self.label_129.setText(_translate("MainWindow", "Weight Distribuition (Kg)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Strain Gauge"))
        self.radioButton_errorLog.setText(_translate("MainWindow", "ErrorLog ON"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Error Log"))
        self.pushButton_Exit.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_PauseProgram.setText(_translate("MainWindow", "PAUSE PROGRAM"))
        self.pushButton_StartProgram.setText(_translate("MainWindow", "START PROGRAM"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Data List"))
        item = self.tableWidget_Package1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Accel X DD"))
        item = self.tableWidget_Package1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Accel Y DD"))
        item = self.tableWidget_Package1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Accel Z DD"))
        item = self.tableWidget_Package1.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Accel X DE"))
        item = self.tableWidget_Package1.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Accel Y DE"))
        item = self.tableWidget_Package1.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Accel Z DE"))
        item = self.tableWidget_Package1.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Accel X TD"))
        item = self.tableWidget_Package1.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Accel Y TD"))
        item = self.tableWidget_Package1.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Accel Z TD"))
        item = self.tableWidget_Package1.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Accel X TE"))
        item = self.tableWidget_Package1.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Accel Y TE"))
        item = self.tableWidget_Package1.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Accel Z TE"))
        item = self.tableWidget_Package1.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Vel DE"))
        item = self.tableWidget_Package1.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Vel DD"))
        item = self.tableWidget_Package1.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "Vel TE"))
        item = self.tableWidget_Package1.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "VEL TD"))
        item = self.tableWidget_Package1.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "RPM"))
        item = self.tableWidget_Package1.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "Beacon"))
        item = self.tableWidget_Package1.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_Package1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VALUE"))
        item = self.tableWidget_Package1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UNIT"))
        __sortingEnabled = self.tableWidget_Package1.isSortingEnabled()
        self.tableWidget_Package1.setSortingEnabled(False)
        item = self.tableWidget_Package1.item(0, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(1, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(2, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(3, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(4, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(5, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(6, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(7, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(8, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(9, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(10, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(11, 1)
        item.setText(_translate("MainWindow", "g"))
        item = self.tableWidget_Package1.item(12, 1)
        item.setText(_translate("MainWindow", "km/h"))
        item = self.tableWidget_Package1.item(13, 1)
        item.setText(_translate("MainWindow", "km/h"))
        item = self.tableWidget_Package1.item(14, 1)
        item.setText(_translate("MainWindow", "km/h"))
        item = self.tableWidget_Package1.item(15, 1)
        item.setText(_translate("MainWindow", "km/h"))
        item = self.tableWidget_Package1.item(16, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package1.item(17, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package1.item(18, 1)
        item.setText(_translate("MainWindow", "ms"))
        self.tableWidget_Package1.setSortingEnabled(__sortingEnabled)
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>PACK 1</p></body></html>"))
        item = self.tableWidget_Package2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "TPS"))
        item = self.tableWidget_Package2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Oil Press"))
        item = self.tableWidget_Package2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fuel P"))
        item = self.tableWidget_Package2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Injectors"))
        item = self.tableWidget_Package2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Susp DE"))
        item = self.tableWidget_Package2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Susp DD"))
        item = self.tableWidget_Package2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Susp TE"))
        item = self.tableWidget_Package2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Susp TD"))
        item = self.tableWidget_Package2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Wheel Pos"))
        item = self.tableWidget_Package2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Bat Current"))
        item = self.tableWidget_Package2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Fan Current"))
        item = self.tableWidget_Package2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Pump Current"))
        item = self.tableWidget_Package2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Brake Press D"))
        item = self.tableWidget_Package2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "Brake Press T"))
        item = self.tableWidget_Package2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_Package2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VALUE"))
        item = self.tableWidget_Package2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UNIT"))
        __sortingEnabled = self.tableWidget_Package2.isSortingEnabled()
        self.tableWidget_Package2.setSortingEnabled(False)
        item = self.tableWidget_Package2.item(0, 1)
        item.setText(_translate("MainWindow", "%"))
        item = self.tableWidget_Package2.item(1, 1)
        item.setText(_translate("MainWindow", "bar"))
        item = self.tableWidget_Package2.item(2, 1)
        item.setText(_translate("MainWindow", "bar"))
        item = self.tableWidget_Package2.item(3, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package2.item(4, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package2.item(5, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package2.item(6, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package2.item(7, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package2.item(8, 1)
        item.setText(_translate("MainWindow", "º"))
        item = self.tableWidget_Package2.item(9, 1)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget_Package2.item(10, 1)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget_Package2.item(11, 1)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget_Package2.item(12, 1)
        item.setText(_translate("MainWindow", "bar"))
        item = self.tableWidget_Package2.item(13, 1)
        item.setText(_translate("MainWindow", "bar"))
        item = self.tableWidget_Package2.item(14, 1)
        item.setText(_translate("MainWindow", "ms"))
        self.tableWidget_Package2.setSortingEnabled(__sortingEnabled)
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p>PACK 2</p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>PACK 3</p></body></html>"))
        item = self.tableWidget_Package3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Bat Voltage"))
        item = self.tableWidget_Package3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Engine Temp.  "))
        item = self.tableWidget_Package3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Oil Temp."))
        item = self.tableWidget_Package3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Brake T DE"))
        item = self.tableWidget_Package3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Brake T DD"))
        item = self.tableWidget_Package3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Brake T TE"))
        item = self.tableWidget_Package3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Brake T TD"))
        item = self.tableWidget_Package3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Fan Temp"))
        item = self.tableWidget_Package3.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Pump Temp"))
        item = self.tableWidget_Package3.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Runners"))
        item = self.tableWidget_Package3.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Vent"))
        item = self.tableWidget_Package3.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Bomba"))
        item = self.tableWidget_Package3.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Mata"))
        item = self.tableWidget_Package3.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "GPS Lat"))
        item = self.tableWidget_Package3.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "GPS Long"))
        item = self.tableWidget_Package3.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "GPS NS"))
        item = self.tableWidget_Package3.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "GPS EW"))
        item = self.tableWidget_Package3.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_Package3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VALUE"))
        item = self.tableWidget_Package3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UNIT"))
        __sortingEnabled = self.tableWidget_Package3.isSortingEnabled()
        self.tableWidget_Package3.setSortingEnabled(False)
        item = self.tableWidget_Package3.item(0, 1)
        item.setText(_translate("MainWindow", "V"))
        item = self.tableWidget_Package3.item(1, 1)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget_Package3.item(2, 1)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget_Package3.item(3, 1)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget_Package3.item(4, 1)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget_Package3.item(5, 1)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget_Package3.item(6, 1)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget_Package3.item(7, 1)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget_Package3.item(8, 1)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget_Package3.item(9, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package3.item(10, 1)
        item.setText(_translate("MainWindow", "ON/OFF"))
        item = self.tableWidget_Package3.item(11, 1)
        item.setText(_translate("MainWindow", "ON/OFF"))
        item = self.tableWidget_Package3.item(12, 1)
        item.setText(_translate("MainWindow", "ON/OFF"))
        item = self.tableWidget_Package3.item(13, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package3.item(14, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package3.item(15, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package3.item(16, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_Package3.item(17, 1)
        item.setText(_translate("MainWindow", "ms"))
        self.tableWidget_Package3.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_StrainGauge.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ext1 DE"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ext2 DE"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ext3 DE"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ext1 DD"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ext2 DD"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ext3 DD"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ext1 TE"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ext2 TE"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Ext3 TE"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Ext1 TD"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Ext2 TD"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Ext3 TD"))
        item = self.tableWidget_StrainGauge.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_StrainGauge.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VALUE"))
        item = self.tableWidget_StrainGauge.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UNIT"))
        __sortingEnabled = self.tableWidget_StrainGauge.isSortingEnabled()
        self.tableWidget_StrainGauge.setSortingEnabled(False)
        item = self.tableWidget_StrainGauge.item(0, 1)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(1, 1)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(2, 1)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(3, 1)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(4, 1)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(5, 1)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(6, 1)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(7, 1)
        item.setText(_translate("MainWindow", "MPa"))
        item = self.tableWidget_StrainGauge.item(8, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_StrainGauge.item(9, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_StrainGauge.item(10, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_StrainGauge.item(11, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tableWidget_StrainGauge.item(12, 1)
        item.setText(_translate("MainWindow", "ms"))
        self.tableWidget_StrainGauge.setSortingEnabled(__sortingEnabled)
        self.pushButton_SaveFile.setText(_translate("MainWindow", "SAVE"))
        self.pushButton_StopSaveFile.setText(_translate("MainWindow", "STOP SAVE"))
        self.label_12.setText(_translate("MainWindow", "Not saving..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUpdate_Serial_Ports.setText(_translate("MainWindow", "Update Serial Ports"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
